### ISSUE TITLE
MRN Issues RESOLVED

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebVR1#8]
As discussed with Naveen Mittal, Sanjay Garg, KB Madan.
1. Intact check of Duplicate Entry on VehicleInTime, VehicleOutTime, VehicleNo.
2. Restore OLD Data.
3. Modify MRN Report to count MRN on Unique VehicleInTime, VehicleOutTime, VehicleNo.

**Comment by hariharan-isgec** [comment]
This Issue is already covered under #3
